/*
Copyright The k3sm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package install

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

// TestSingleNodeServerPlistIsByteIdentical pins the single-node server plist
// to the bytes the installer rendered before it knew any embedded-etcd HA flag.
// Both goldens were rendered by the release that preceded that change (the
// stock template is the one TestInstallRendersAgentDaemonWhenJoining already pins,
// shared rather than copied), and neither is regenerated by this test: an HA change that moves one byte of a single-node install fails
// here instead of reaching a running cluster as a re-rendered daemon.
func TestSingleNodeServerPlistIsByteIdentical(t *testing.T) {
	for _, tc := range []struct {
		golden string
		cfg    Config
	}{
		{"server.plist.golden", Config{}},
		{"serverplist-carried-args.golden", Config{ExtraServerArgs: []string{"--mesh-ip", "100.64.0.1", "--registry-port", "5000"}}},
	} {
		t.Run(tc.golden, func(t *testing.T) {
			want, err := os.ReadFile(filepath.Join("testdata", tc.golden))
			if err != nil {
				t.Fatalf("read the golden: %v", err)
			}
			if got := ServerPlist(tc.cfg); !bytes.Equal(got, want) {
				t.Errorf("the single-node server plist changed:\n--- got\n%s\n--- want\n%s", got, want)
			}
		})
	}
}
