#!/usr/bin/env bash
#
# mlx-serve — build the k3sm MLX serving image.
#
# The image is a FROM-scratch, COPY-only native darwin/arm64 image: a
# python-build-standalone CPython dist plus the serving engine's wheel closure,
# staged ON THE BUILD HOST by uv and then packaged verbatim by `k3sm build`.
# There is no RUN step anywhere, because the builder packages files and does not
# execute them — so everything that would have been a RUN happens here, in this
# script, before the tree is handed over.
#
# What the image does NOT contain: model weights. Weights are a volume concern
# (HF_HOME points at the cache mount), never image content.
#
# Every version is pinned: the interpreter by exact python-build-standalone
# release URL below, the engine and its whole closure by requirements.lock with
# a hash for every artifact. A lockfile line without a hash, or with a direct
# (git+) URL, is refused before anything is downloaded.
#
# Usage:
#   hack/images/mlx-serve/build.sh                 # stage, build, walk-verify
#   hack/images/mlx-serve/build.sh --restage       # rebuild the staged tree
#   hack/images/mlx-serve/build.sh --no-verify     # skip the walk-verify step
#   hack/images/mlx-serve/build.sh --print-dockerfile
#   hack/images/mlx-serve/build.sh --check-lock <file>
#
# Requires: macOS on Apple silicon, uv, python3, and a `k3sm` binary. It needs
# no root, writes only under its work dir, and pushes nothing anywhere — see
# README.md for the publish step.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"

# ---- pins -------------------------------------------------------------------
# The interpreter, pinned twice: by uv's version key AND by the exact
# python-build-standalone artifact URL that key must resolve to. The key alone
# is not a pin — a later uv ships a newer python-build-standalone build of the
# same CPython patch version — so the URL is asserted before staging.
PY_KEY="cpython-3.12.14-macos-aarch64-none"
PY_URL="https://releases.astral.sh/github/python-build-standalone/releases/download/20260825/cpython-3.12.14%2B20260825-aarch64-apple-darwin-install_only_stripped.tar.gz"
PY_BIN="bin/python3.12"
# The uv that generated requirements.lock. Older uv is refused rather than
# tried: the JSON interpreter listing this script pins against is not in every
# release, and a silent skip of the URL assertion would un-pin the interpreter.
UV_MIN="0.12.7"

# The serving contract, and the one flag the engine will not work without.
# At its defaults this engine serves ONE request at a time and answers HTTP 503
# to every other concurrent client — with a green /health and a green readiness
# probe, so nothing downstream catches it. --continuous-batching is therefore
# part of the image, not an operator tuning knob. Measured evidence:
# hack/spike/m8/findings-s5.md.
ENGINE_MODULE="vllm_mlx.cli"
SERVE_PORT="8000"
# The engine binds 127.0.0.1 by default, which is unreachable through a Service.
SERVE_HOST="0.0.0.0"
# The cache mount: weights live on a volume mounted here, never in the image.
HF_HOME_PATH="/models"

DEFAULT_TAG="ghcr.io/k3sm-io/mlx-serve:0.4.1"

# ---- options ----------------------------------------------------------------
WORK="${K3SM_MLX_WORK:-$HOME/.cache/k3sm/mlx-serve}"
TAG="$DEFAULT_TAG"
OUT=""
STAGE=""
RESTAGE=0
VERIFY=1
K3SM_BIN="${K3SM_BIN:-}"

usage() {
	# The leading comment block, minus the shebang and the leading "# ".
	awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); print; next } NR > 1 { exit }' "$0"
}

die() { echo "mlx-serve: $*" >&2; exit 2; }

# ---- the Dockerfile ---------------------------------------------------------
# COPY-only by construction: FROM scratch, one COPY, and metadata. It is written
# OUTSIDE the build context, because `COPY . /` would otherwise absorb it into
# the image it describes.
#
# ENTRYPOINT is the interpreter Mach-O ITSELF (/bin/python3.12), not the
# /bin/python3 symlink and not a shell wrapper: argv[0] is what the runtime
# verifies a signature on, so it has to be the real file. The model is NOT named
# here — it arrives as the container's args, so one image serves any model.
print_dockerfile() {
	cat <<EOF
# Generated by hack/images/mlx-serve/build.sh — do not edit by hand.
FROM scratch
COPY . /
ENV HF_HOME=$HF_HOME_PATH
ENV HF_HUB_DISABLE_TELEMETRY=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PATH=/bin
LABEL org.opencontainers.image.title="mlx-serve"
LABEL org.opencontainers.image.description="OpenAI-compatible MLX serving for k3sm on Apple silicon"
LABEL org.opencontainers.image.licenses="Apache-2.0"
LABEL org.opencontainers.image.source="https://github.com/k3sm-io/k3sm"
LABEL io.k3sm.mlx-serve.engine="$(engine_pin)"
LABEL io.k3sm.mlx-serve.python="$PY_KEY"
EXPOSE $SERVE_PORT/tcp
ENTRYPOINT ["/$PY_BIN", "-m", "$ENGINE_MODULE", "serve", "--continuous-batching", "--host", "$SERVE_HOST", "--port", "$SERVE_PORT"]
EOF
}

# engine_pin echoes the engine requirement exactly as requirements.in pins it,
# so the image label cannot drift from what is actually installed.
engine_pin() {
	grep -E '^[a-zA-Z0-9]' "$HERE/requirements.in" | head -1
}

# ---- lockfile ---------------------------------------------------------------
# verify_lock refuses anything that would let an unpinned artifact into the
# image. It is the same check `uv pip install --require-hashes` makes, run
# BEFORE the network is touched and with a message that says what to do.
verify_lock() {
	local lock="$1" report reqs hashes
	[ -f "$lock" ] || die "lockfile not found: $lock"

	# One pass: a requirement is a line starting in column 1; the --hash lines
	# that follow it belong to it. Every requirement must be an exact == pin
	# with at least one hash, and must not be a direct (git+/URL) requirement,
	# which cannot carry a hash by construction.
	report="$(awk '
		function flush(   ) {
			if (name == "") return
			if (line ~ /git\+/ || line ~ /@ +[a-z]+:/ || line ~ /file:\/\//)
				printf "  REFUSED (direct URL, cannot be hash-pinned): %s\n", name
			else if (name !~ /==/)
				printf "  REFUSED (not an exact == pin): %s\n", name
			else if (n == 0)
				printf "  REFUSED (no --hash): %s\n", name
			name = ""
		}
		/^[ \t]*#/ { next }
		/^[^ \t]/  { flush(); name = $1; line = $0; n = 0; reqs++; next }
		/--hash=/   { if (name != "") { n++; hashes++ } }
		END { flush(); printf "COUNT %d %d\n", reqs, hashes }
	' "$lock")"

	reqs="$(printf '%s\n' "$report" | awk '/^COUNT/ { print $2 }')"
	hashes="$(printf '%s\n' "$report" | awk '/^COUNT/ { print $3 }')"
	if [ "${reqs:-0}" -eq 0 ]; then
		die "$lock has no requirements — refusing to build an empty payload"
	fi
	if printf '%s\n' "$report" | grep -q '^  REFUSED'; then
		printf '%s\n' "$report" | grep '^  REFUSED' >&2
		echo "mlx-serve: $lock is not fully hash-pinned." >&2
		echo "           Regenerate it with 'uv pip compile --generate-hashes' — see README.md." >&2
		return 1
	fi
	echo "  lockfile: $reqs requirements, $hashes hashes, all pinned"
}

# ---- host + tool checks -----------------------------------------------------
require_host() {
	[ "$(uname -s)" = "Darwin" ] || die "this image is darwin/arm64; build it on a Mac"
	# A translated (Rosetta) shell reports x86_64 and would stage x86_64 wheels
	# into an arm64 image, so it is refused rather than warned about.
	[ "$(uname -m)" = "arm64" ] || die "build from a native arm64 shell (uname -m says $(uname -m); a Rosetta-translated shell would stage the wrong wheels)"
	command -v python3 >/dev/null 2>&1 || die "python3 not found (Xcode command line tools)"
}

require_uv() {
	UV="${K3SM_MLX_UV:-$(command -v uv 2>/dev/null || true)}"
	[ -n "$UV" ] && [ -x "$UV" ] || die "uv not found — install it (https://docs.astral.sh/uv/) and re-run; this script stages the tree with uv and will not guess a substitute"
	local have
	have="$("$UV" --version 2>/dev/null | awk '{print $2}')"
	[ -n "$have" ] || die "cannot read a version from '$UV --version'"
	if [ "$(printf '%s\n%s\n' "$UV_MIN" "$have" | sort -V | head -1)" != "$UV_MIN" ]; then
		die "uv $have is older than the pinned minimum $UV_MIN (requirements.lock was generated with $UV_MIN)"
	fi
	echo "  uv: $have ($UV)"
}

require_k3sm() {
	[ -n "$K3SM_BIN" ] || K3SM_BIN="$(command -v k3sm 2>/dev/null || true)"
	[ -n "$K3SM_BIN" ] && [ -x "$K3SM_BIN" ] || die "no k3sm binary — build one (CGO_ENABLED=1 go build -o /tmp/k3sm ./cmd/k3sm) and pass it as K3SM_BIN"
	echo "  k3sm: $K3SM_BIN"
}

# ---- staging ----------------------------------------------------------------
# assert_interpreter_pin fails if uv's manifest no longer maps the pinned key to
# the pinned artifact. Bumping the interpreter is then a deliberate edit of both
# constants at the top of this file, never a silent consequence of a uv upgrade.
assert_interpreter_pin() {
	local got
	got="$("$UV" python list --all-versions --output-format json 2>/dev/null |
		python3 -c '
import json, sys
key = sys.argv[1]
try:
    entries = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for e in entries:
    if e.get("key") == key:
        print(e.get("url") or "")
        break
' "$PY_KEY")"
	[ -n "$got" ] || die "uv does not offer $PY_KEY (or its JSON listing could not be read)"
	[ "$got" = "$PY_URL" ] || die "uv maps $PY_KEY to
    $got
  but this script pins
    $PY_URL
  Bump PY_URL deliberately (and re-measure the image) or use uv $UV_MIN."
}

stage_tree() {
	export UV_PYTHON_INSTALL_DIR="$WORK/python"
	export UV_CACHE_DIR="${UV_CACHE_DIR:-$WORK/uv-cache}"
	mkdir -p "$UV_PYTHON_INSTALL_DIR"

	local stamp want
	# Beside the stage, never inside it: a stamp file in the tree would ship in
	# the image.
	stamp="${STAGE}.stamp"
	want="$PY_KEY $(shasum -a 256 "$HERE/requirements.lock" | awk '{print $1}')"
	if [ "$RESTAGE" -eq 0 ] && [ -x "$STAGE/$PY_BIN" ] && [ -f "$stamp" ] && [ "$(cat "$stamp")" = "$want" ]; then
		echo "  stage: up to date ($STAGE) — pass --restage to rebuild"
		return 0
	fi

	echo "==> stage the interpreter ($PY_KEY)"
	"$UV" python install "$PY_KEY" >/dev/null
	assert_interpreter_pin

	# uv keeps a version ALIAS symlink beside the dist whose target is ABSOLUTE
	# (cpython-3.12-macos-aarch64-none -> /abs/.../cpython-3.12.14-...). The
	# builder refuses absolute symlinks, so the RESOLVED versioned directory is
	# what gets staged — never the install dir that holds the alias.
	local dist="$UV_PYTHON_INSTALL_DIR/$PY_KEY"
	[ -d "$dist" ] || die "expected the resolved interpreter dir at $dist"
	[ ! -L "$dist" ] || die "$dist is a symlink; stage the resolved versioned directory, not uv's alias"

	rm -rf "$STAGE"
	mkdir -p "$(dirname "$STAGE")"
	cp -Rc "$dist/." "$STAGE/" 2>/dev/null || cp -R "$dist/." "$STAGE/"

	# uv stamps its managed interpreters EXTERNALLY-MANAGED. An image rootfs is
	# not uv-managed, so the marker is REMOVED rather than defeated with
	# --break-system-packages, which would also silence a real misconfiguration.
	find "$STAGE" -name EXTERNALLY-MANAGED -delete

	echo "==> install the engine closure (--require-hashes)"
	"$UV" pip install --python "$STAGE/$PY_BIN" --require-hashes -r "$HERE/requirements.lock"

	# The mount point for the weights volume, so HF_HOME resolves even before
	# anything is mounted there.
	mkdir -p "$STAGE${HF_HOME_PATH}"

	echo "==> precompile bytecode"
	# Without this every pod writes its own __pycache__ into its copy-on-write
	# clone of the rootfs, breaking sharing for exactly the model-architecture
	# modules the lockfile could not know would be imported. -s/-p rewrite the
	# recorded source paths to their in-image locations; unchecked-hash .pyc are
	# never revalidated against source mtimes, which a tar round-trip perturbs.
	if ! "$STAGE/$PY_BIN" -m compileall -q -j 0 --invalidation-mode unchecked-hash \
		-s "$STAGE" -p / "$STAGE/lib/python3.12" >/dev/null 2>&1; then
		echo "  note: some modules did not precompile (usually vendored py2 samples) — not fatal"
	fi

	echo "$want" > "$stamp"
}

# assert_stageable rejects the symlink shapes the builder refuses, here, where
# the offending entry can be named — the builder's own error names only the
# context root.
assert_stageable() {
	local bad=0 l target
	while IFS= read -r l; do
		target="$(readlink "$l")"
		case "$target" in
			/*) echo "  ABSOLUTE symlink: ${l#"$STAGE"/} -> $target" >&2; bad=$((bad + 1)); continue ;;
		esac
		if [ ! -e "$l" ]; then
			echo "  DANGLING symlink: ${l#"$STAGE"/} -> $target" >&2; bad=$((bad + 1))
		fi
	done < <(find "$STAGE" -type l)
	[ "$bad" -eq 0 ] || die "$bad symlink(s) the builder will refuse (it accepts relative, resolvable, in-context links only)"
}

# assert_context_budget guards the builder's own 2 GiB context ceiling, which
# binds before any image-size budget does.
assert_context_budget() {
	local bytes limit
	bytes="$(find "$STAGE" -type f -exec stat -f '%z' {} + | awk '{s += $1} END {printf "%d", s}')"
	limit=$((2 * 1024 * 1024 * 1024))
	awk -v b="$bytes" -v l="$limit" 'BEGIN { printf "  staged payload: %.2f GB (%.0f%% of the builder'"'"'s %.0f GB context budget)\n", b/1073741824, 100*b/l, l/1073741824 }'
	[ "$bytes" -lt "$limit" ] || die "the staged tree exceeds the builder's context budget; prune the payload before building"
}

# ---- main -------------------------------------------------------------------
while [ $# -gt 0 ]; do
	case "$1" in
		--tag) TAG="${2:-}"; [ -n "$TAG" ] || die "--tag needs a value"; shift 2 ;;
		--output) OUT="${2:-}"; [ -n "$OUT" ] || die "--output needs a value"; shift 2 ;;
		--stage) STAGE="${2:-}"; [ -n "$STAGE" ] || die "--stage needs a value"; shift 2 ;;
		--work) WORK="${2:-}"; [ -n "$WORK" ] || die "--work needs a value"; shift 2 ;;
		--restage) RESTAGE=1; shift ;;
		--no-verify) VERIFY=0; shift ;;
		--print-dockerfile) print_dockerfile; exit 0 ;;
		--check-lock) verify_lock "${2:?--check-lock needs a file}"; exit $? ;;
		-h|--help) usage; exit 0 ;;
		*) die "unknown flag: $1 (try --help)" ;;
	esac
done

[ -n "$STAGE" ] || STAGE="$WORK/stage"
[ -n "$OUT" ] || OUT="$WORK/oci"

echo "==> preflight"
require_host
verify_lock "$HERE/requirements.lock"
require_uv
require_k3sm

mkdir -p "$WORK"
stage_tree
assert_stageable
assert_context_budget

echo "==> package (k3sm build --format oci)"
print_dockerfile > "$WORK/Dockerfile"
rm -rf "$OUT"
"$K3SM_BIN" build --file "$WORK/Dockerfile" --tag "$TAG" --format oci --output "$OUT" "$STAGE"

DIGEST="$(python3 -c '
import json, sys
idx = json.load(open(sys.argv[1]))
print(idx["manifests"][0]["digest"])
' "$OUT/index.json")"

if [ "$VERIFY" -eq 1 ]; then
	echo "==> walk-verify the payload"
	"$HERE/walk-verify.sh" --layout "$OUT"
fi

cat <<EOF

==> built
  tag:    $TAG
  digest: $DIGEST
  layout: $OUT
  pin:    ${TAG%%:*}@$DIGEST

Publish it (the credential is read from the environment, never from argv):

  K3SM_REGISTRY_TOKEN=<token> k3sm image push $OUT $TAG

Record the digest above — the operator pins the image by digest, and the tag is
display-only. See README.md.
EOF
